function A = A_arm(in1,in2)
%A_ARM
%    A = A_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Dec-2020 14:41:39

I1 = in2(7,:);
I2 = in2(8,:);
Ir1 = in2(9,:);
Ir2 = in2(10,:);
N1 = in2(11,:);
N2 = in2(12,:);
c1 = in2(1,:);
c2 = in2(2,:);
l1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = c1.^2;
t6 = c2.^2;
t7 = Ir2.*N2;
t8 = l1.*t2;
t9 = cos(t4);
t10 = l1.*t3;
t11 = sin(t4);
t12 = c2.*t9;
t13 = c2.*t11;
t14 = t8+t12;
t15 = t10+t13;
t16 = t13.*t15.*2.0;
t17 = t12.*t14.*2.0;
t18 = t16+t17;
t19 = (m2.*t18)./2.0;
t20 = t7+t19;
A = reshape([I1+Ir2+Ir1.*N1.^2+(m1.*(t2.^2.*t5.*2.0+t3.^2.*t5.*2.0))./2.0+(m2.*(t14.^2.*2.0+t15.^2.*2.0))./2.0,t20,t20,I2+N2.*t7+(m2.*(t6.*t9.^2.*2.0+t6.*t11.^2.*2.0))./2.0],[2,2]);
