function pan_position = get_pan_position(in1,in2)
%GET_PAN_POSITION
%    PAN_POSITION = GET_PAN_POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Dec-2020 14:41:41

l1 = in2(3,:);
l2 = in2(4,:);
pA = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t9 = l2./2.0;
t10 = pA./2.0;
t5 = l1.*t2;
t6 = cos(t4);
t7 = l1.*t3;
t8 = sin(t4);
t12 = t9+t10;
t11 = -t5;
pan_position = reshape([t7+pA.*t8,t11-pA.*t6,t7+l2.*t8,t11-l2.*t6,t7+t8.*t12,t11-t6.*t12],[2,3]);
