function J = J_arm(in1,in2)
%J_ARM
%    J = J_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Dec-2020 14:10:50

l1 = in2(3,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l2.*t3;
t6 = l2.*t4;
J = reshape([t5+l1.*cos(th1),t6+l1.*sin(th1),t5,t6],[2,2]);
