function J_pan = J_pan_arm(in1,in2)
%J_PAN_ARM
%    J_PAN = J_PAN_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Dec-2020 14:10:50

l1 = in2(3,:);
l2 = in2(4,:);
pA = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t5 = l2./2.0;
t6 = pA./2.0;
t3 = cos(t2);
t4 = sin(t2);
t7 = t5+t6;
t8 = t3.*t7;
t9 = t4.*t7;
J_pan = reshape([t8+l1.*cos(th1),t9+l1.*sin(th1),t8,t9],[2,2]);
