function out1 = pan_parallel(in1,in2)
%PAN_PARALLEL
%    OUT1 = PAN_PARALLEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Dec-2020 14:41:41

th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
out1 = [sin(t2);-cos(t2)];
