function out1 = pan_velocity_interpolation(in1,in2,t_param)
%PAN_VELOCITY_INTERPOLATION
%    OUT1 = PAN_VELOCITY_INTERPOLATION(IN1,IN2,T_PARAM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Nov-2020 17:21:20

dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(3,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = sin(t2);
out1 = [dth1.*(l1.*cos(th1)+l2.*t3.*t_param)+dth2.*l2.*t3.*t_param;dth1.*(l1.*sin(th1)+l2.*t4.*t_param)+dth2.*l2.*t4.*t_param];
