function out1 = pan_position_interpolation(in1,in2,t_param)
%PAN_POSITION_INTERPOLATION
%    OUT1 = PAN_POSITION_INTERPOLATION(IN1,IN2,T_PARAM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    15-Nov-2020 16:56:30

l1 = in2(3,:);
l2 = in2(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
out1 = [l1.*sin(th1)+l2.*t_param.*sin(t2);-l1.*cos(th1)-l2.*t_param.*cos(t2)];
