function out1 = pan_velocity_interpolation(in1,in2,t_param)
%PAN_VELOCITY_INTERPOLATION
%    OUT1 = PAN_VELOCITY_INTERPOLATION(IN1,IN2,T_PARAM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Nov-2020 19:29:59

dth1 = in1(3,:);
dth2 = in1(4,:);
l1 = in2(3,:);
l2 = in2(4,:);
pA = in2(16,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t5 = -pA;
t3 = cos(t2);
t4 = sin(t2);
t8 = l2+t5;
t6 = pA.*t3;
t7 = pA.*t4;
t9 = t3.*t8.*t_param;
t10 = t4.*t8.*t_param;
out1 = [dth2.*(t6+t9)+dth1.*(t6+t9+l1.*cos(th1));dth2.*(t7+t10)+dth1.*(t7+t10+l1.*sin(th1))];
