function V = potential_energy_doublepend(in1,in2)
%POTENTIAL_ENERGY_DOUBLEPEND
%    V = POTENTIAL_ENERGY_DOUBLEPEND(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Oct-2020 18:32:41

c1 = in2(1,:);
c2 = in2(2,:);
g = in2(13,:);
l1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
V = -g.*m2.*(l1.*t2+c2.*cos(th1+th2))-c1.*g.*m1.*t2;
