function V = potential_energy_arm(in1,in2)
%POTENTIAL_ENERGY_ARM
%    V = POTENTIAL_ENERGY_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-Nov-2020 19:29:58

c1 = in2(1,:);
c2 = in2(2,:);
g = in2(15,:);
l1 = in2(3,:);
m1 = in2(5,:);
m2 = in2(6,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = cos(th1);
V = -g.*m2.*(l1.*t2+c2.*cos(th1+th2))-c1.*g.*m1.*t2;
