function A = A_pancake(in1,in2)
%A_PANCAKE
%    A = A_PANCAKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 14:12:41

I = in2(3,:);
m = in2(2,:);
A = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,I],[3,3]);
