function out1 = get_pancake_velocity(in1,in2)
%GET_PANCAKE_VELOCITY
%    OUT1 = GET_PANCAKE_VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 12:07:43

dth = in1(6,:);
dx = in1(4,:);
dy = in1(5,:);
l = in2(1,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
t4 = (dth.*l.*t2)./2.0;
t5 = (dth.*l.*t3)./2.0;
out1 = reshape([dx+t5,dy-t4,dx-t5,dy+t4],[2,2]);
