function out1 = get_pancake_position(in1,in2)
%GET_PANCAKE_POSITION
%    OUT1 = GET_PANCAKE_POSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 12:07:43

l = in2(1,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = (l.*t2)./2.0;
t5 = (l.*t3)./2.0;
out1 = reshape([-t4+x,-t5+y,t4+x,t5+y],[2,2]);
