function out1 = get_pancake_com_velocity(in1,in2)
%GET_PANCAKE_COM_VELOCITY
%    OUT1 = GET_PANCAKE_COM_VELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 14:12:42

dx = in1(4,:);
dy = in1(5,:);
out1 = [dx;dy];
