function JB = jacobian_pk_B(in1,in2)
%JACOBIAN_PK_B
%    JB = JACOBIAN_PK_B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 14:12:43

l = in2(1,:);
th = in1(3,:);
JB = reshape([1.0,0.0,0.0,0.0,1.0,0.0,l.*sin(th).*(-1.0./2.0),(l.*cos(th))./2.0,0.0],[3,3]);
