function JA = jacobian_pk_A(in1,in2)
%JACOBIAN_PK_A
%    JA = JACOBIAN_PK_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 12:07:44

l = in2(1,:);
th = in1(3,:);
JA = reshape([1.0,0.0,0.0,0.0,1.0,0.0,(l.*sin(th))./2.0,l.*cos(th).*(-1.0./2.0),0.0],[3,3]);
