function keypoints = keypoints_pancake(in1,in2)
%KEYPOINTS_PANCAKE
%    KEYPOINTS = KEYPOINTS_PANCAKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    28-Oct-2020 01:25:33

l = in2(1,:);
th = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(th);
t3 = sin(th);
t4 = (l.*t2)./2.0;
t5 = (l.*t3)./2.0;
keypoints = reshape([x,y,-t4+x,-t5+y,t4+x,t5+y],[2,3]);
