function out1 = pk_velocity_interpolation(in1,in2,t_param)
%PK_VELOCITY_INTERPOLATION
%    OUT1 = PK_VELOCITY_INTERPOLATION(IN1,IN2,T_PARAM)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 12:07:44

dth = in1(6,:);
dx = in1(4,:);
dy = in1(5,:);
l = in2(1,:);
th = in1(3,:);
t2 = cos(th);
t3 = sin(th);
out1 = [dx+dth.*((l.*t3)./2.0-l.*t3.*t_param);dy-dth.*((l.*t2)./2.0-l.*t2.*t_param)];
