function V = potential_energy_pancake(in1,in2)
%POTENTIAL_ENERGY_PANCAKE
%    V = POTENTIAL_ENERGY_PANCAKE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Nov-2020 12:07:43

g = in2(4,:);
m = in2(2,:);
y = in1(2,:);
V = g.*m.*y;
